name: Teste de CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build da aplicação
        run: |
          docker-compose build

      - name: Rodar os testes
        run: |
          docker-compose run app-forum-api mvn test
